# -*- coding: utf-8 -*-
"""archaea_media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0NNPgup-sHq20RzXiUF3lmWdSd7AHqt
"""

import matplotlib.pyplot as plt
import pandas as pd
import io

# ==========================================================
# 1. VISUALIZATION LOGIC (The "Clean" Code)
# ==========================================================

def generate_archaea_charts(csv_data):
    # Read the internal string as if it were a file
    df = pd.read_csv(io.StringIO(csv_data))

    groups = df['Archaea Group'].unique()
    fig, axes = plt.subplots(1, len(groups), figsize=(15, 5))
    fig.suptitle('Distribution of Media for Different Archaea Groups', fontsize=16)

    # Styling
    greyscale = ['#808080', '#D3D3D3']

    for i, group in enumerate(groups):
        subset = df[df['Archaea Group'] == group]

        # Ensure axes is subscriptable even if there's only 1 group
        ax = axes[i] if len(groups) > 1 else axes

        ax.pie(
            subset['Count'],
            labels=subset['Media'],
            autopct='%1.1f%%',
            startangle=140,
            colors=greyscale,
            wedgeprops={'edgecolor': 'white'}
        )
        ax.set_title(group, fontweight='bold')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

# ==========================================================
# 2. DATA STORAGE (Hidden at the bottom)
# ==========================================================

# This string acts as your "hidden" data file
raw_data = """Archaea Group,Media,Count,Percent
Acidophilic,FreshWater Medium,2,66.66
Acidophilic,DSMZ 88,1,33.33
Syntrophic,Basal Medium,1,100.0
Ammonia Oxidizing,Synthetic Crenarchaeota Medium,7,87.5
Ammonia Oxidizing,Artificial Freshwater Medium,1,12.5"""

if __name__ == "__main__":
    generate_archaea_charts(raw_data)